# GOOPS_INCLUDE_DIR = goops.h
# GOOPS_LIBRARIES = goops.so
# GOOPS_FOUND = true if goops is found

IF(GOOPS_INCLUDE_DIRS)
  FIND_PATH(GOOPS_INCLUDE_DIR goops.h  ${GOOPS_INCLUDE_DIRS})
  FIND_LIBRARY(GOOPS_LIBRARIES goops ${GOOPS_LIBRARY_DIRS})
ENDIF(GOOPS_INCLUDE_DIRS)

SET(GOOPS_FOUND FALSE)
IF(GOOPS_INCLUDE_DIR AND GOOPS_LIBRARIES)
  MESSAGE(STATUS "GOOPS_INCLUDE_DIR=${GOOPS_INCLUDE_DIR}")
  MESSAGE(STATUS "GOOPS_LIBRARIES=${GOOPS_LIBRARIES}")
  SET(GOOPS_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
   GOOPS_INCLUDE_DIR
   GOOPS_LIBRARIES
   GOOPS_FOUND
)

